"""EvolutionaryModelDiscovery: Automated agent rule generation and 
importance evaluation for agent-based models with Genetic Programming.
Copyright (C) 2018  Chathika Gunaratne
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>."""


"""Adapted by Gayani PDP Senanayake, 2025
Changes made:
- Introduced Adaptive Genetic Programming (AGP) features:
  • Dynamic population resizing during evolution
  • Early stopping after N stagnant generations
  • Elite individual retention across multiple runs
- Modified the evolve() method to support high-stochasticity ABM scenarios
- Designed for use with stochastic rule discovery in Python-based ABMs """



from typing import Callable, Any, List, Dict
import multiprocessing
# from concurrent.futures import ProcessPoolExecutor
import random
from inspect import isclass

from deap import algorithms, gp, creator, base, tools
import pandas as pd
import numpy as np
import time

from .Util import *
from .ABMEvaluator import (
    set_objective_function,
    set_model_factors,
    set_model_init_data,
    set_python_writer,
    evaluate,
    run_python_based_simulation,
)
from .PythonWriter import PythonWriter


class SimpleDEAPGP:
    def __init__(
        self,
        model_init_data: Dict,
        ModelFactors: "EvolutionaryModelDiscovery.ModelFactors",
        python_writer: PythonWriter,
    ) -> None:
        """
        Genetic program that handles the evolution of the agent-based model rule.

        :param model_init_data: Dict of model initialization properties.
        :param ModelFactors: ModelFactors module generated by EvolutionaryModelDiscovery 
                                by parsing the annotated NetLogo model files
        """

        self._mutation_rate = 0.2
        self._crossover_rate = 0.8
        self._generations = 10
        self._run_count = 1
        self._pop_init_size = 2
        self.seen_rules_in_run = {}
        self.best_overall_individuals = []
        set_model_init_data(model_init_data)
        set_model_factors(ModelFactors)
        set_python_writer(python_writer)
        self._pset = ModelFactors.get_DEAP_primitive_set()
        self._setup_DEAP_GP()



    def _setup_DEAP_GP(self) -> None:
        """
        Sets up the DEAP GP.

        """
        creator.create("FitnessMax", base.Fitness, weights=(1.0,))
        creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
        creator.create(
            "IndividualMin", gp.PrimitiveTree, fitness=creator.FitnessMin, model_path=None
        )
        creator.create(
            "IndividualMax", gp.PrimitiveTree, fitness=creator.FitnessMax, model_path=None
        )

        self._toolbox = base.Toolbox()
        # Attribute generator
        self._toolbox.register(
            "expr_init", genGrow, pset=self._pset, min_=2, max_=10
        )

        # Structure initializers
        self._toolbox.register(
            "individual",
            tools.initIterate,
            creator.IndividualMin,
            self._toolbox.expr_init,
        )
        self._toolbox.register(
            "population", tools.initRepeat, list, self._toolbox.individual
        )
        # self._toolbox.register("setupCommands", tools.initRepeat, setupCommands )
        # self._toolbox.register("evaluate", self.evaluate)
        self._toolbox.register("select", tools.selTournament, tournsize=3)
        # self._toolbox.register("select", self.custom_tournament_selection, tournsize=5)
        self._toolbox.register("mate", gp.cxOnePoint)
        self._toolbox.register("expr_mut", genGrow, min_=2, max_=3)
        self._toolbox.register(
            "mutate",
            gp.mutUniform,
            expr=self._toolbox.expr_mut,
            pset=self._pset,
        )
        # print("_toolbox setup completed")

        self.hof = tools.HallOfFame(1)
        # global self._stats
        self._stats = tools.Statistics(get_values)  #
        self._stats.register("avg", np.mean)
        self._stats.register("std", np.std)
        self._stats.register("min", np.min)
        self._stats.register("max", np.max)


    def set_mutation_rate(self, mutation_rate: float) -> None:
        self._mutation_rate = mutation_rate

    def set_crossover_rate(self, crossover_rate: float) -> None:
        self._crossover_rate = crossover_rate

    def set_generations(self, generations: int) -> None:
        self._generations = generations

    def set_population_size(self, population_size: int) -> None:
        self._pop_init_size = population_size

    def set_objective_function(self, objective_function: Callable) -> None:
        set_objective_function(objective_function)

    def set_depth(self, min: int, max: int) -> None:
        self._toolbox.register(
            "expr_init", genGrow, pset=self._pset, min_=min, max_=max
        )
        self._toolbox.register(
            "expr_mut", genGrow, pset=self._pset, min_=min, max_=max
        )

    def set_is_minimize(self, is_minimize: bool):
        if is_minimize:
            self._toolbox.register(
                "individual",
                tools.initIterate,
                creator.IndividualMin,
                self._toolbox.expr_init,
            )
        else:
            self._toolbox.register(
                "individual",
                tools.initIterate,
                creator.IndividualMax,
                self._toolbox.expr_init,
            )
        self._toolbox.register(
            "population", tools.initRepeat, list, self._toolbox.individual
        )

    def evolve(
        self, num_procs: int = multiprocessing.cpu_count(), verbose=__debug__, best_individuals=None, start_time=None
    ):

        """
        This method implements an Adaptive Genetic Programming (AGP) algorithm
        extending the standard evolutionary loop from DEAP (Chapter 7 of [Back2000]_).
        It integrates mechanisms designed to improve search efficiency and robustness
        when discovering stochastic agent rules for ABMs.

        Key extensions to the classic EA process include:

        - **Adaptive population sizing**: the population dynamically shrinks after the discovery of a better-performing individual to promote exploitation and save computation.
        - **Local early stopping**: if no improvement in fitness is seen over a set number of generations, the current run is terminated.
        - **Elite retention across runs**: the best individuals from each run are carried into the next to preserve high-quality solutions and improve convergence.
        - **Stochastic model evaluation**: evolved individuals are evaluated using multiple simulation runs of a Python-based ABM (e.g., StationSim) to ensure robust fitness estimation.

        :param num_procs: Number of processes for parallel evaluation (default: all cores).
        :param verbose: Whether to print evolution progress.
        :param best_individuals: Elite individuals passed from the previous run for reuse.
        :param start_time: Optional timestamp for logging.

        :returns:
            - Final population of the run,
            - A DEAP `Logbook` containing evolutionary statistics,
            - A DataFrame of factor scores for each evaluated rule,
            - The five best-performing individuals from the current run.

        Pseudocode for a single adaptive evolutionary run:

            initialize(population)
            evaluate(population)
            while not early_stopping:
                select(parents)
                apply crossover & mutation
                evaluate(offspring)
                update best solution
                adjust population size if improved

        Multiple such runs are executed, and elites are retained between them.

        .. note::
            This function assumes that `toolbox.mate`, `toolbox.mutate`, `toolbox.select`,
            and `toolbox.evaluate` are properly registered.

        .. [Back2000] Bäck, Fogel, and Michalewicz. *Evolutionary Computation 1:
            Basic Algorithms and Operators*. 2000.
        """

        if start_time is None:
            start_time = self.model_init_data.get('start_time')

        new_population = self._toolbox.population(n=self._pop_init_size)

        # Combine with best individuals if available
        if best_individuals:
            population = best_individuals + new_population
        else:
            population = new_population

        for off in population:
            del off.fitness.values

        logbook = tools.Logbook()
        logbook.header = ["gen", "nevals"] + (
            self._stats.fields if self._stats else []
        )

        # Identify which individuals need evaluation
        invalid_ind = [ind for ind in population if not ind.fitness.valid]

        factorScores = pd.DataFrame()
        num_procs = multiprocessing.cpu_count() if num_procs < 1 else num_procs

        with multiprocessing.pool.ThreadPool(num_procs) as pool:
            results = list(pool.imap(evaluate, invalid_ind))

        end_time = time.time()
        total_time = end_time - start_time

        fitnesses = []
        factorScores = pd.DataFrame()
        for result in results:
            fitnesses.append(result.Fitness)
            # fs = result
            # fs["Gen"] = 0
            # fs["Fitness"] = fs.Fitness[0]
            # fs["Time"] = total_time
            # factorScores = factorScores.append(
            #     fs, ignore_index=True, sort=False
            # )
        for ind, fit in zip(invalid_ind, fitnesses):
            ind.fitness.values = fit

        update_unique_individuals(invalid_ind, self.seen_rules_in_run)
        for ind in invalid_ind:
            rule_str = str(ind)
            if rule_str in self.seen_rules_in_run:
                previous_fitness = self.seen_rules_in_run[rule_str][0]
                current_fitness = ind.fitness.values[0]
                if current_fitness > previous_fitness:  # Lower fitness is better
                    ind.fitness.values = (previous_fitness,)

        for i, result in enumerate(results):
            fs = result
            fs["Gen"] = 0
            fs["Original_Fitness"] = fs.Fitness[0]  # Store original fitness
            fs["Fitness"] = invalid_ind[i].fitness.values[0]  # Store updated fitness
            fs["Time"] = total_time
            factorScores = factorScores.append(
                fs, ignore_index=True, sort=False
            )

        if self.hof is not None:
            self.hof.update(population)

        record = self._stats.compile(population) if self._stats else {}
        logbook.record(gen=0, nevals=len(invalid_ind), **record)
        if verbose:
            print(logbook.stream)

        Local_best_ind = min(population, key=lambda ind: ind.fitness.values[0])
        Local_best_fitness = Local_best_ind.fitness.values[0]
        consecutive_threshold = 10  # Number of consecutive generations to check
        n = 0
        m = len(population)
        for gen in range(1, self._generations + 1):
            # Select the next generation individuals
            offspring = self._toolbox.select(population, m)

            # Vary the pool of individuals
            offspring = algorithms.varAnd(
                offspring,
                self._toolbox,
                self._crossover_rate,
                self._mutation_rate,
            )
            for off in offspring:
                del off.fitness.values

            # Evaluate the individuals with an invalid fitness
            invalid_ind = [ind for ind in offspring if not ind.fitness.valid]

            with multiprocessing.pool.ThreadPool(num_procs) as pool:
                results = list(pool.imap(evaluate, invalid_ind))

            end_time = time.time()
            total_time = end_time - start_time

            fitnesses = []
            for result in results:
                fitnesses.append(result.Fitness)
                # fs = result
                # fs["Gen"] = gen
                # fs["Fitness"] = fs.Fitness[0]
                # fs["Time"] = total_time
                # factorScores = factorScores.append(
                #     fs, ignore_index=True, sort=False
                # )

            for ind, fit in zip(invalid_ind, fitnesses):
                ind.fitness.values = fit

            update_unique_individuals(invalid_ind, self.seen_rules_in_run)
            fitness_val = []
            for ind in invalid_ind:
                rule_str = str(ind)
                current_fitness = ind.fitness.values[0]
                fitness_val.append(current_fitness)
                if rule_str in self.seen_rules_in_run:
                    previous_fitness = self.seen_rules_in_run[rule_str][0]
                    if current_fitness > previous_fitness:  # Lower fitness is better
                        ind.fitness.values = (previous_fitness,)

            for i, result in enumerate(results):
                fs = result
                fs["Gen"] = gen
                fs["Original_Fitness"] = fs.Fitness[0]  # Store original fitness
                fs["Fitness"] = invalid_ind[i].fitness.values[0]  # Store updated fitness
                fs["Time"] = total_time
                factorScores = factorScores.append(
                    fs, ignore_index=True, sort=False
                )

            if self.hof is not None:
                self.hof.update(offspring)

            # Replace the current population by the offspring
            population[:] = offspring

            # Append the current generation statistics to the logbook
            record = self._stats.compile(population) if self._stats else {}
            logbook.record(gen=gen, nevals=len(invalid_ind), **record)
            if verbose:
                print(logbook.stream)

            current_best_fitness = min(fitness_val)
            if current_best_fitness >= Local_best_fitness:
                n += 1
                if n >= consecutive_threshold:
                    print(f"Termination criteria met at generation {gen}")
                    print(f"Best fitness of last {consecutive_threshold} generations all above {Local_best_fitness}")
                    break
            else:
                Local_best_fitness = current_best_fitness
                n = 0
                # Decrease the population size by 5, but don't go below 10
                m = max(10, m - 5)

            if gen % 10 == 0:
                csv_filename = f'factor_scores_gen_{gen}.csv'
                factorScores.to_csv(csv_filename, index=False)
                print(f"Factor scores saved to {csv_filename}")

            best_overall = sorted(
                [entry[1] for entry in self.seen_rules_in_run.values()],
                key=lambda ind: ind.fitness.values[0]
            )[:5]

        return (
            population,
            logbook,
            factorScores,
            best_overall
        )

def update_unique_individuals(invalid_ind, seen_rules_in_run):
    """
    Update the unique individuals.
    Now tracks rules and their fitness, updating when better versions are found.
    """
    # Process all individuals
    for ind in invalid_ind:
            rule_str = str(ind)
            current_fitness = ind.fitness.values[0]

            if rule_str in seen_rules_in_run:
                previous_fitness = seen_rules_in_run[rule_str][0]
                # Update if new version has better fitness
                if current_fitness < previous_fitness:
                    seen_rules_in_run[rule_str] = (current_fitness, ind)
            else:
                # New rule, add it
                seen_rules_in_run[rule_str] = (current_fitness, ind)


def genGrow(pset, min_: int, max_: int, type_: Any = None) -> List[Any]:
    """Generate an expression where each leaf might have a different depth
    between *min* and *max*.

    :param pset: Primitive set from which primitives are selected.
    :param min_: Minimum height of the produced trees.
    :param max_: Maximum Height of the produced trees.
    :param type_: The type that should return the tree when called, when
                  :obj:`None` (default) the type of :pset: (pset.ret)
                  is assumed.
    :returns: A grown tree with leaves at possibly different depths.
    """

    def condition(height, depth):
        """Expression generation stops when the depth is equal to height
        or when it is randomly determined that a node should be a terminal.
        """
        return depth == height or (
            depth >= min_ and random.random() < 0.5
        )

    return generate(pset, min_, max_, condition, type_)


def generate(
    pset, min_: int, max_: int, condition: Callable, type_: Any = None
) -> List[Any]:
    """Generate a Tree as a list of list. The tree is build
    from the root to the leaves, and it stop growing when the
    condition is fulfilled.

    :param pset: Primitive set from which primitives are selected.
    :param min_: Minimum height of the produced trees.
    :param max_: Maximum Height of the produced trees.
    :param condition: The condition is a function that takes two arguments,
                    the height of the tree to build and the current
                    depth in the tree.
    :param type_: The type that should return the tree when called, when
                :obj:`None` (default) the type of :pset: (pset.ret)
                is assumed.
    :returns: A grown tree with leaves at possibly different depths
            dependending on the condition function.
    :raises: TypeError if no primitives or terminals of required type
    """
    validTree = False
    while not validTree:
        if type_ is None:
            type_ = pset.ret
        expr = []
        height = random.randint(min_, max_)
        stack = [(0, type_)]
        validTree = True
        while len(stack) != 0:
            depth, type_ = stack.pop()
            if condition(height, depth):
                if len(pset.terminals[type_]) > 0:
                    term = random.choice(pset.terminals[type_])
                    if isclass(term):
                        term = term()
                    expr.append(term)
                else:
                    if len(pset.primitives[type_]) > 0:
                        prim = random.choice(pset.primitives[type_])
                        expr.append(prim)
                        for arg in reversed(prim.args):
                            stack.append((depth + 1, arg))
                    else:
                        raise TypeError(
                            f"Invalid tree! No primitives or terminals of type {type_}"
                        )
            else:
                if len(pset.primitives[type_]) > 0:
                    prim = random.choice(pset.primitives[type_])
                    expr.append(prim)
                    for arg in reversed(prim.args):
                        stack.append((depth + 1, arg))
                elif len(pset.terminals[type_]) > 0:
                    term = random.choice(pset.terminals[type_])
                    if isclass(term):
                        term = term()
                    expr.append(term)
                else:
                    raise TypeError(
                        f"Invalid tree! No primitives or terminals of type {type_}"
                    )
    return expr


def get_values(ind: Any) -> List[float]:
    """
    Returns fitness values of a GP individual. Used by stats object
    """
    return ind.fitness.values

